services:
  ai-gateway:
    image: ai-gateway:local
    container_name: ai-gateway-local
    restart: unless-stopped
    networks: [ai-net]
    ports: ["9000:8000"]
    env_file: [.env]
    volumes:
      - ./doc-templates:/app/doc-templates
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=3).status==200 else 1)"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

  ai-gateway-proxy:
    image: nginx:1.27-alpine
    container_name: ai-gateway-proxy
    restart: unless-stopped
    networks: [ai-net]
    ports: ["443:443"]
    volumes:
      - /opt/ai/nginx/ai-gateway.conf:/etc/nginx/nginx.conf:ro
      - /opt/ai/tls:/etc/nginx/certs:ro

networks:
  ai-net:
    external: true
