name: build-ai-gateway

on:
  push:
    branches: [ main ]
    paths:
      - "ai-gateway/**"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push ai-gateway
        uses: docker/build-push-action@v6
        with:
          context: ./ai-gateway
          file: ./ai-gateway/Dockerfile
          push: true
          # Включи кеш при желании:
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/ai-gateway:latest
            ghcr.io/${{ github.repository_owner }}/ai-gateway:${{ github.sha }}
